name: Deploy on Successful Build

on:
  workflow_run:
    workflows: ["Build Svelte using Bun"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Exit if the branch is not master
        run: |
          if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
            echo "Branch is not master, exiting."
            exit 0
          fi

      - name: Setup Cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb
        shell: bash

      - name: Setup ssh cloudflared config
        run: |
          mkdir -p ~/.ssh
          printf "Host sshlol.kylerchin.com\nProxyCommand /usr/bin/cloudflared access ssh --hostname %%h" > ~/.ssh/config
          echo "${{ secrets.MEERKAT_SERVER }}" > ~/.ssh/known_hosts
        shell: bash
        
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
        shell: bash

      - name: SSH
        run: |
          ssh runner@sshlol.kylerchin.com "echo '${{ secrets.SUDO_PASSWD }}' | sudo -S bash -c 'chown -R kyler /opt/catenary-frontend'; echo '${{ secrets.SUDO_PASSWD }}' | sudo -S -u kyler bash -c 'source /home/kyler/.bash_profile ; cd /opt/catenary-frontend; git pull -X theirs; bun install; bun run build'; echo '${{ secrets.SUDO_PASSWD }}' | sudo -S systemctl restart transitfrontend.service"
        shell: bash
