name: Release
on:
  push:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-and-push-frontend-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Compile Frontend
      uses: redhat-actions/buildah-build@v2
      with:
        image: catenarytransit/catenaryfrontend
        tags: ${{ github.sha }} latest
        containerfiles: | 
          ./Dockerfile

    - name: Push Frontend To ghcr.io
      id: push-to-ghcr-frontend
      uses: redhat-actions/push-to-registry@v2
      with:
        image: catenarytransit/catenaryfrontend
        tags: ${{ github.sha }} latest
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGE_TOKEN }}
